server:
  port: ${port:40401}
  tomcat:
    max-http-header-size: 8192
spring:
  application:
    name: th-treehole-train
  datasource:
    druid:
      url: jdbc:mysql://10.0.43.60:3306/th_train?characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
    pagehelper:
      helper‐dialect: mysql

eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
      prefer‐ip‐address: true #将自己的ip地址注册到Eureka服务中
      ip‐address: ${IP_ADDRESS:127.0.0.1}
      instance‐id: ${spring.application.name}:${server.port} #指定实例id
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作 没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000 #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mapper/StudentMapper.xml,classpath*:mybatis/mapper/ClassMapper.xml,classpath*:mybatis/mapper/TeacherMapper.xml,classpath*:mybatis/mapper/CostMapper.xml,classpath*:mybatis/mapper/LeaveMapper.xml,classpath*:mybatis/mapper/CourseMapper.xml,classpath*:mybatis/mapper/CourseTypeMapper.xml,classpath*:mybatis/mapper/PhaseCourseMapper.xml,classpath*:mybatis/mapper/PhaseMapper.xml,classpath*:mybatis/mapper/TeacherCourseMapper.xml,classpath*:mybatis/mapper/DocumentMapper.xml
  type-aliases-package: com.treehole.framework.domain.train