server:
  port: ${port:40401}
spring:
  application:
    name: th-treehole-train
  datasource:
    druid:
      url: jdbc:mysql://10.0.43.60:3306/th_train?characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
    pagehelper:
      helper‐dialect: mysql

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mapper/StudentMapper.xml,classpath*:mybatis/mapper/ClassMapper.xml,classpath*:mybatis/mapper/TeacherMapper.xml,classpath*:mybatis/mapper/CostMapper.xml,classpath*:mybatis/mapper/LeaveMapper.xml,classpath*:mybatis/mapper/CourseMapper.xml,classpath*:mybatis/mapper/CourseTypeMapper.xml,classpath*:mybatis/mapper/PhaseCourseMapper.xml,classpath*:mybatis/mapper/PhaseMapper.xml,classpath*:mybatis/mapper/TeacherCourseMapper.xml
  type-aliases-package: com.treehole.framework.domain.train