server:
  port: 31450
spring:
  application:
    name: th-service-manage-media-processor
#  data:
#    mongodb:
#      uri:  mongodb://root:root@localhost:27017
#      database: xc_media
  datasource:
    druid:
      url: jdbc:mysql://10.0.43.60:3306/th_courses_online?characterEncoding=utf-8
      username: root
      password: root
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
#rabbitmq配置
  rabbitmq:
    host: 10.0.43.60
    port: 5672
    username: root
    password: root
    virtual-host: /
xc-service-manage-media:
  mq:
    queue-media-video-processor: queue_media_video_processor
    routingkey-media-video: routingkey_media_video
  video-location: G:/develop/video/
  ffmpeg-path: E:/Tools/ffmpeg-20191109/bin/ffmpeg.exe