vsftpd:
  host: 10.0.43.64
  port: 21
  username: ftpuser
  password: ftpuser
  basePath: /home/ftpuser
  filepath: /
server:
  port: 10086
spring:
  application:
    name: th-document-manage
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 500MB
  resources:
    static-locations: classpath:/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.0.43.60:3306/th_document?characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    solr:
      host: http://10.0.42.151:8080/solr


eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: ${EUREKA_SERVER:http://localhost:50101/eureka/}
  instance:
    prefer‐ip‐address: true #将自己的ip地址注册到Eureka服务中
    ip‐address: ${IP_ADDRESS:127.0.0.1}
    instance‐id: ${spring.application.name}:${server.port} #指定实例id
